import os
import re
import logging
import psycopg

from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ConversationHandler,
    ContextTypes,
    filters,
)

# =========================
# SETTINGS
# =========================

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")
ADMIN_ID = os.getenv("ADMIN_ID")

PORT = int(os.getenv("PORT", "10000"))
RENDER_EXTERNAL_URL = os.getenv("RENDER_EXTERNAL_URL")

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

logger = logging.getLogger(__name__)


# =========================
# DATABASE
# =========================

def get_connection():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set")

    return psycopg.connect(DATABASE_URL)


def init_database():
    with get_connection() as conn:
        with conn.cursor() as cur:

            # WORKERS
            cur.execute(
                "CREATE TABLE IF NOT EXISTS workers "
                "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "telegram_id BIGINT, name TEXT, phone TEXT, service TEXT, "
                "area TEXT, price TEXT, created_at TIMESTAMPTZ DEFAULT NOW())"
            )

            # ORDERS
            cur.execute(
                "CREATE TABLE IF NOT EXISTS orders "
                "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "telegram_id BIGINT, name TEXT, phone TEXT, service TEXT, "
                "address TEXT, problem TEXT, created_at TIMESTAMPTZ DEFAULT NOW())"
            )

            # ANNOUNCEMENTS
            cur.execute(
                "CREATE TABLE IF NOT EXISTS announcements "
                "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "telegram_id BIGINT, name TEXT, phone TEXT, service TEXT, "
                "address TEXT, budget TEXT, details TEXT, "
                "created_at TIMESTAMPTZ DEFAULT NOW())"
            )

            # Агар эски жадвалларда telegram_id йўқ бўлса,
            # автоматик қўшилади.
            cur.execute(
                "ALTER TABLE workers "
                "ADD COLUMN IF NOT EXISTS telegram_id BIGINT"
            )

            cur.execute(
                "ALTER TABLE orders "
                "ADD COLUMN IF NOT EXISTS telegram_id BIGINT"
            )

            cur.execute(
                "ALTER TABLE announcements "
                "ADD COLUMN IF NOT EXISTS telegram_id BIGINT"
            )

        conn.commit()


# =========================
# SERVICE NORMALIZATION
# =========================

def normalize_service_name(text):
    if not text:
        return ""

    text = str(text).casefold()

    text = re.sub(
        r"[🔧⚡📱💻🧹🪑👨‍🔧]",
        "",
        text,
    )

    replacements = {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "yo",
        "ж": "j",
        "з": "z",
        "и": "i",
        "й": "y",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "x",
        "ц": "ts",
        "ч": "ch",
        "ш": "sh",
        "щ": "sh",
        "ъ": "",
        "ы": "y",
        "ь": "",
        "э": "e",
        "ю": "yu",
        "я": "ya",
        "қ": "q",
        "ғ": "g",
        "ҳ": "h",
        "ў": "o",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def canonical_service(text):
    """
    Хизмат номини асосий категорияга келтиради.
    """

    normalized = normalize_service_name(text)

    if not normalized:
        return ""

    # Компьютер таъмири вариантлари
    if (
        "kompyuter" in normalized
        or "komyuter" in normalized
        or "komputer" in normalized
    ):
        return "kompyuter"

    # Сантехник вариантлари
    if (
        "santexnik" in normalized
        or "santehnik" in normalized
    ):
        return "santexnik"

    # Электрик
    if "elektrik" in normalized:
        return "elektrik"

    # Телефон таъмири
    if "telefon" in normalized:
        return "telefon"

    # Уй тозалаш
    if "uy tozalash" in normalized or "tozalash" in normalized:
        return "tozalash"

    # Мебель
    if "mebel" in normalized:
        return "mebel"

    return normalized


def service_matches(selected_service, worker_services):
    """
    Устанинг бир нечта хизмати бўлса ҳам,
    танланган хизмат билан аниқ мослаштиради.
    """

    selected = canonical_service(selected_service)

    if not selected or not worker_services:
        return False

    parts = re.split(
        r"[,;/\n]+",
        str(worker_services),
    )

    for part in parts:

        worker_service = canonical_service(part)

        if worker_service == selected:
            return True

    return False


SERVICES = [
    "🔧 Сантехник",
    "⚡ Электрик",
    "📱 Телефон таъмири",
    "💻 Компьютер таъмири",
    "🧹 Уй тозалаш",
    "🪑 Мебель таъмири",
]


# =========================
# MENUS
# =========================

def main_menu():
    return ReplyKeyboardMarkup(
        [
            ["🔧 Хизматлар"],
            ["👨‍🔧 Уста чақириш"],
            ["📢 Эълон бериш"],
            ["Алоқа", "👤 Менинг профилим"],
        ],
        resize_keyboard=True,
    )


def services_menu():
    return ReplyKeyboardMarkup(
        [
            ["🔧 Сантехник"],
            ["⚡ Электрик"],
            ["📱 Телефон таъмири"],
            ["💻 Компьютер таъмири"],
            ["🧹 Уй тозалаш"],
            ["🪑 Мебель таъмири"],
            ["⬅️ Бош меню"],
        ],
        resize_keyboard=True,
    )


# =========================
# COMMON MENU / CANCEL
# =========================

MAIN_MENU_BUTTONS = [
    "🔧 Хизматлар",
    "👨‍🔧 Уста чақириш",
    "📢 Эълон бериш",
    "Алоқа",
    "👤 Менинг профилим",
    "⬅️ Бош меню",
]


MAIN_MENU_PATTERN = (
    r"^(🔧 Хизматлар|👨‍🔧 Уста чақириш|📢 Эълон бериш|"
    r"Алоқа|👤 Менинг профилим|⬅️ Бош меню|"
    r"🔧 Сантехник|⚡ Электрик|📱 Телефон таъмири|"
    r"💻 Компьютер таъмири|🧹 Уй тозалаш|🪑 Мебель таъмири)$"
)


async def cancel_to_main(update, context):
    """
    Форма ичида меню тугмаси босилса:
    маълумот сақланмайди ва форма тугайди.
    """

    context.user_data.clear()

    await update.message.reply_text(
        "🛠 Керакли хизматни танланг:",
        reply_markup=main_menu(),
    )

    return ConversationHandler.END


async def cancel_command(update, context):
    """
    /cancel командаси.
    """

    context.user_data.clear()

    await update.message.reply_text(
        "❌ Амал бекор қилинди.\n\n"
        "🛠 Керакли хизматни танланг:",
        reply_markup=main_menu(),
    )

    return ConversationHandler.END


# =========================
# START
# =========================

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):

    context.user_data.clear()

    await update.message.reply_text(
        "🛠 Osh Service ботга хуш келибсиз!\n"
        "Керакли хизматни танланг:",
        reply_markup=main_menu(),
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):

    await update.message.reply_text(
        "📌 Osh Service\n\n"
        "/start — бош меню\n"
        "/help — ёрдам\n"
        "/cancel — жорий амални бекор қилиш\n"
        "/admin — админ панель\n"
        "/workers — усталар\n"
        "/orders — буюртмалар\n"
        "/announcements — эълонлар\n"
        "/stats — статистика"
    )


async def services(update: Update, context: ContextTypes.DEFAULT_TYPE):

    await update.message.reply_text(
        "🔧 Қайси хизмат керак?",
        reply_markup=services_menu(),
    )


# =========================
# CUSTOMER ORDER
# =========================

NAME, PHONE, ADDRESS, PROBLEM = range(4)


async def service_selected(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):

    service = update.message.text

    context.user_data.clear()
    context.user_data["service"] = service

    workers = []

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT name, service, area, price, phone "
                "FROM workers ORDER BY id DESC"
            )

            rows = cur.fetchall()

            for row in rows:

                worker_service = row[1]

                if service_matches(
                    service,
                    worker_service,
                ):
                    workers.append(row)

    if workers:

        message = "👨‍🔧 Мос усталар:\n\n"

        for i, row in enumerate(workers[:10], 1):

            name, worker_service, area, price, phone = row

            message += (
                f"#{i} {name}\n"
                f"🔧 Хизмат: {worker_service}\n"
                f"📍 Ҳудуд: {area}\n"
                f"💰 Нархи: {price}\n"
                f"📞 Телефон: {phone}\n\n"
            )

        await update.message.reply_text(message)

    else:

        await update.message.reply_text(
            "😔 Ҳозирча бу хизмат бўйича "
            "рўйхатдан ўтган уста топилмади."
        )

    await update.message.reply_text(
        f"Танланган хизмат: {service}\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return NAME


async def customer_name(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Исмингизни ёзинг:"
        )
        return NAME

    context.user_data["name"] = text

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return PHONE


async def customer_phone(update, context):

    phone = update.message.text.strip()

    digits = re.sub(r"\D", "", phone)

    if len(digits) < 7:
        await update.message.reply_text(
            "❗ Телефон рақами нотўғри.\n"
            "Илтимос, телефон рақамингизни қайта ёзинг:"
        )
        return PHONE

    context.user_data["phone"] = phone

    await update.message.reply_text(
        "📍 Манзилингизни ёзинг:"
    )

    return ADDRESS


async def customer_address(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Манзилингизни ёзинг:"
        )
        return ADDRESS

    context.user_data["address"] = text

    await update.message.reply_text(
        "📝 Муаммони ёзинг:"
    )

    return PROBLEM


async def customer_problem(update, context):

    problem = update.message.text.strip()

    if not problem:
        await update.message.reply_text(
            "❗ Муаммони ёзинг:"
        )
        return PROBLEM

    context.user_data["problem"] = problem

    user = update.effective_user
    data = context.user_data

    order_id = None
    matching_workers = []

    # =========================
    # 1. SAVE ORDER + FIND WORKERS
    # =========================

    with get_connection() as conn:
        with conn.cursor() as cur:

            # Буюртмани Supabase'га сақлаймиз
            cur.execute(
                "INSERT INTO orders "
                "(telegram_id, name, phone, service, address, problem) "
                "VALUES (%s, %s, %s, %s, %s, %s) "
                "RETURNING id",
                (
                    user.id,
                    data["name"],
                    data["phone"],
                    data["service"],
                    data["address"],
                    data["problem"],
                ),
            )

            result = cur.fetchone()

            if result:
                order_id = result[0]

            # Барча усталарни оламиз
            cur.execute(
                "SELECT telegram_id, name, service, area, price "
                "FROM workers "
                "ORDER BY id DESC"
            )

            rows = cur.fetchall()

            # Танланган хизматга мос усталарни аниқлаймиз
            for row in rows:

                worker_telegram_id = row[0]
                worker_service = row[2]

                if service_matches(
                    data["service"],
                    worker_service,
                ):
                    matching_workers.append(row)

        conn.commit()

    # =========================
    # 2. SEND ORDER TO WORKERS
    # =========================

    sent_count = 0

    for worker in matching_workers:

        worker_telegram_id = worker[0]
        worker_name = worker[1]

        # Telegram ID бўлмаса, хабар юбормаймиз
        if not worker_telegram_id:
            logger.warning(
                f"Worker {worker_name} has no telegram_id"
            )
            continue

        worker_message = (
            "🔔 ЯНГИ БУЮРТМА!\n\n"
            f"📌 Буюртма №{order_id}\n\n"
            f"👤 Исм: {data['name']}\n"
            f"📞 Телефон: {data['phone']}\n"
            f"🔧 Хизмат: {data['service']}\n"
            f"📍 Манзил: {data['address']}\n"
            f"📝 Муаммо: {data['problem']}\n\n"
            "📲 Мижоз билан боғланинг."
        )

        try:

            await context.bot.send_message(
                chat_id=int(worker_telegram_id),
                text=worker_message,
            )

            sent_count += 1

            logger.info(
                f"Order #{order_id} sent to worker "
                f"{worker_name} "
                f"(telegram_id={worker_telegram_id})"
            )

        except Exception as e:

            logger.exception(
                f"Failed to send order #{order_id} "
                f"to worker {worker_name} "
                f"(telegram_id={worker_telegram_id}): {e}"
            )

    # =========================
    # 3. CUSTOMER CONFIRMATION
    # =========================

    if sent_count > 0:

        worker_result_text = (
            f"👨‍🔧 {sent_count} та мос устага "
            "буюртма юборилди."
        )

    elif matching_workers:

        worker_result_text = (
            "⚠️ Мос уста топилди, лекин ҳозирча "
            "унга Telegram хабарини юбориб бўлмади."
        )

    else:

        worker_result_text = (
            "ℹ️ Ҳозирча бу хизмат бўйича "
            "мос уста топилмади."
        )

    await update.message.reply_text(
        "🔔 ЯНГИ БУЮРТМА!\n\n"
        f"📌 Буюртма №{order_id}\n"
        f"👤 Исм: {data['name']}\n"
        f"📞 Телефон: {data['phone']}\n"
        f"🔧 Хизмат: {data['service']}\n"
        f"📍 Манзил: {data['address']}\n"
        f"📝 Муаммо: {data['problem']}\n\n"
        "✅ Буюртмангиз қабул қилинди.\n"
        f"{worker_result_text}",
        reply_markup=main_menu(),
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# WORKER REGISTRATION
# =========================

WORKER_NAME, WORKER_PHONE, WORKER_SERVICE, WORKER_AREA, WORKER_PRICE = range(
    5, 10
)


async def worker_start(update, context):

    context.user_data.clear()

    await update.message.reply_text(
        "👨‍🔧 Уста бўлиб рўйхатдан ўтиш\n\n"
        "👤 Исм ва фамилиянгизни ёзинг:"
    )

    return WORKER_NAME


async def worker_name(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Исм ва фамилиянгизни ёзинг:"
        )
        return WORKER_NAME

    context.user_data["worker_name"] = text

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return WORKER_PHONE


async def worker_phone(update, context):

    phone = update.message.text.strip()

    digits = re.sub(r"\D", "", phone)

    if len(digits) < 7:
        await update.message.reply_text(
            "❗ Телефон рақами нотўғри.\n"
            "Илтимос, телефон рақамингизни қайта ёзинг:"
        )
        return WORKER_PHONE

    context.user_data["worker_phone"] = phone

    await update.message.reply_text(
        "🔧 Қайси хизматларни кўрсатасиз?\n\n"
        "Масалан:\n"
        "Santehnik, kafel, ariston"
    )

    return WORKER_SERVICE


async def worker_service(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Хизматларингизни ёзинг:"
        )
        return WORKER_SERVICE

    context.user_data["worker_service"] = text

    await update.message.reply_text(
        "📍 Қайси ҳудудда ишлайсиз?"
    )

    return WORKER_AREA


async def worker_area(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Ишлайдиган ҳудудингизни ёзинг:"
        )
        return WORKER_AREA

    context.user_data["worker_area"] = text

    await update.message.reply_text(
        "💰 Хизмат нархини ёзинг:"
    )

    return WORKER_PRICE


async def worker_price(update, context):

    price = update.message.text.strip()

    if not price:
        await update.message.reply_text(
            "❗ Хизмат нархини ёзинг:"
        )
        return WORKER_PRICE

    context.user_data["worker_price"] = price

    user = update.effective_user
    data = context.user_data

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "INSERT INTO workers "
                "(telegram_id, name, phone, service, area, price) "
                "VALUES (%s, %s, %s, %s, %s, %s)",
                (
                    user.id,
                    data["worker_name"],
                    data["worker_phone"],
                    data["worker_service"],
                    data["worker_area"],
                    data["worker_price"],
                ),
            )

        conn.commit()

    await update.message.reply_text(
        "✅ Сиз уста сифатида муваффақиятли "
        "рўйхатдан ўтдингиз!\n\n"
        f"👤 {data['worker_name']}\n"
        f"📞 {data['worker_phone']}\n"
        f"🔧 {data['worker_service']}\n"
        f"📍 {data['worker_area']}\n"
        f"💰 {data['worker_price']}",
        reply_markup=main_menu(),
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# ANNOUNCEMENT
# =========================

ANN_NAME, ANN_PHONE, ANN_SERVICE, ANN_ADDRESS, ANN_BUDGET, ANN_DETAILS = range(
    10, 16
)


async def announcement_start(update, context):

    context.user_data.clear()

    await update.message.reply_text(
        "📢 Эълон бериш\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return ANN_NAME


async def ann_name(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Исмингизни ёзинг:"
        )
        return ANN_NAME

    context.user_data["ann_name"] = text

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return ANN_PHONE


async def ann_phone(update, context):

    phone = update.message.text.strip()

    digits = re.sub(r"\D", "", phone)

    if len(digits) < 7:
        await update.message.reply_text(
            "❗ Телефон рақами нотўғри.\n"
            "Илтимос, телефон рақамингизни қайта ёзинг:"
        )
        return ANN_PHONE

    context.user_data["ann_phone"] = phone

    await update.message.reply_text(
        "🔧 Қайси хизмат керак?"
    )

    return ANN_SERVICE


async def ann_service(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Қайси хизмат кераклигини ёзинг:"
        )
        return ANN_SERVICE

    context.user_data["ann_service"] = text

    await update.message.reply_text(
        "📍 Манзилни ёзинг:"
    )

    return ANN_ADDRESS


async def ann_address(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Манзилни ёзинг:"
        )
        return ANN_ADDRESS

    context.user_data["ann_address"] = text

    await update.message.reply_text(
        "💰 Бюджетингизни ёзинг:"
    )

    return ANN_BUDGET


async def ann_budget(update, context):

    text = update.message.text.strip()

    if not text:
        await update.message.reply_text(
            "❗ Бюджетингизни ёзинг:"
        )
        return ANN_BUDGET

    context.user_data["ann_budget"] = text

    await update.message.reply_text(
        "📝 Қўшимча маълумотни ёзинг:"
    )

    return ANN_DETAILS


async def ann_details(update, context):

    details = update.message.text.strip()

    if not details:
        await update.message.reply_text(
            "❗ Қўшимча маълумотни ёзинг:"
        )
        return ANN_DETAILS

    context.user_data["ann_details"] = details

    user = update.effective_user
    data = context.user_data

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "INSERT INTO announcements "
                "(telegram_id, name, phone, service, address, budget, details) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s)",
                (
                    user.id,
                    data["ann_name"],
                    data["ann_phone"],
                    data["ann_service"],
                    data["ann_address"],
                    data["ann_budget"],
                    data["ann_details"],
                ),
            )

        conn.commit()

    await update.message.reply_text(
        "📢 ЯНГИ ЭЪЛОН!\n\n"
        f"👤 Исм: {data['ann_name']}\n"
        f"📞 Телефон: {data['ann_phone']}\n"
        f"🔧 Хизмат: {data['ann_service']}\n"
        f"📍 Манзил: {data['ann_address']}\n"
        f"💰 Бюджет: {data['ann_budget']}\n"
        f"📝 Тафсилот: {data['ann_details']}\n\n"
        "✅ Эълонингиз қабул қилинди.",
        reply_markup=main_menu(),
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# PROFILE
# =========================

async def profile(update, context):

    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT name, phone, service, area, price "
                "FROM workers "
                "WHERE telegram_id = %s "
                "ORDER BY id DESC LIMIT 1",
                (user.id,),
            )

            row = cur.fetchone()

    if not row:

        await update.message.reply_text(
            "👤 Сизнинг уста профилингиз "
            "ҳозирча топилмади.",
            reply_markup=main_menu(),
        )

        return

    name, phone, service, area, price = row

    await update.message.reply_text(
        "👤 Менинг профилим\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Ҳудуд: {area}\n"
        f"💰 Нархи: {price}",
        reply_markup=main_menu(),
    )


# =========================
# CONTACT
# =========================

async def contact(update, context):

    await update.message.reply_text(
        "📞 Алоқа\n\n"
        "Osh Service администратори билан "
        "боғланиш учун администраторга мурожаат қилинг.",
        reply_markup=main_menu(),
    )


# =========================
# ADMIN
# =========================

def is_admin(update):

    if not ADMIN_ID:
        return False

    return str(update.effective_user.id) == str(ADMIN_ID)


async def admin(update, context):

    if not is_admin(update):

        await update.message.reply_text(
            "⛔ Сизда админ ҳуқуқи йўқ."
        )

        return

    await update.message.reply_text(
        "🔐 Админ панель\n\n"
        "/workers — усталар\n"
        "/orders — буюртмалар\n"
        "/announcements — эълонлар\n"
        "/stats — статистика"
    )


async def workers_command(update, context):

    if not is_admin(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT name, service, area, price, phone, created_at "
                "FROM workers ORDER BY id DESC"
            )

            rows = cur.fetchall()

    if not rows:

        await update.message.reply_text(
            "👨‍🔧 Ҳозирча усталар йўқ."
        )

        return

    message = "👨‍🔧 УСТАЛАР:\n\n"

    for i, row in enumerate(rows, 1):

        name, service, area, price, phone, created_at = row

        message += (
            f"#{i} {name}\n"
            f"🔧 Хизмат: {service}\n"
            f"📍 Ҳудуд: {area}\n"
            f"💰 Нархи: {price}\n"
            f"📞 Телефон: {phone}\n"
            f"🕒 {created_at}\n\n"
        )

    await update.message.reply_text(message)


async def orders_command(update, context):

    if not is_admin(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT name, phone, service, address, problem, created_at "
                "FROM orders ORDER BY id DESC"
            )

            rows = cur.fetchall()

    if not rows:

        await update.message.reply_text(
            "🔔 Ҳозирча буюртмалар йўқ."
        )

        return

    message = "🔔 БУЮРТМАЛАР:\n\n"

    for i, row in enumerate(rows, 1):

        name, phone, service, address, problem, created_at = row

        message += (
            f"#{i}\n"
            f"👤 {name}\n"
            f"📞 {phone}\n"
            f"🔧 {service}\n"
            f"📍 {address}\n"
            f"📝 {problem}\n"
            f"🕒 {created_at}\n\n"
        )

    await update.message.reply_text(message)


async def announcements_command(update, context):

    if not is_admin(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT name, phone, service, address, budget, "
                "details, created_at "
                "FROM announcements ORDER BY id DESC"
            )

            rows = cur.fetchall()

    if not rows:

        await update.message.reply_text(
            "📢 Ҳозирча эълонлар йўқ."
        )

        return

    message = "📢 ЭЪЛОНЛАР:\n\n"

    for i, row in enumerate(rows, 1):

        (
            name,
            phone,
            service,
            address,
            budget,
            details,
            created_at,
        ) = row

        message += (
            f"#{i}\n"
            f"👤 {name}\n"
            f"📞 {phone}\n"
            f"🔧 {service}\n"
            f"📍 {address}\n"
            f"💰 {budget}\n"
            f"📝 {details}\n"
            f"🕒 {created_at}\n\n"
        )

    await update.message.reply_text(message)


async def stats_command(update, context):

    if not is_admin(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute("SELECT COUNT(*) FROM workers")
            workers_count = cur.fetchone()[0]

            cur.execute("SELECT COUNT(*) FROM orders")
            orders_count = cur.fetchone()[0]

            cur.execute("SELECT COUNT(*) FROM announcements")
            announcements_count = cur.fetchone()[0]

    total = (
        workers_count
        + orders_count
        + announcements_count
    )

    await update.message.reply_text(
        "📊 СТАТИСТИКА\n\n"
        f"👨‍🔧 Усталар: {workers_count}\n"
        f"🔔 Буюртмалар: {orders_count}\n"
        f"📢 Эълонлар: {announcements_count}\n"
        f"📌 Жами: {total}"
    )


# =========================
# MENU HANDLER
# =========================

async def menu_handler(update, context):

    text = update.message.text

    if text == "🔧 Хизматлар":
        return await services(update, context)

    if text == "👨‍🔧 Уста чақириш":
        return await worker_start(update, context)

    if text == "📢 Эълон бериш":
        return await announcement_start(update, context)

    if text == "Алоқа":
        return await contact(update, context)

    if text == "👤 Менинг профилим":
        return await profile(update, context)

    if text == "⬅️ Бош меню":

        await update.message.reply_text(
            "🛠 Керакли хизматни танланг:",
            reply_markup=main_menu(),
        )

        return

    if text in SERVICES:
        return await service_selected(update, context)


# =========================
# ERROR HANDLER
# =========================

async def error_handler(update, context):

    logger.error(
        "Exception while handling update:",
        exc_info=context.error,
    )


# =========================
# MAIN
# =========================

def main():

    if not TOKEN:
        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN is not set"
        )

    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL is not set"
        )

    init_database()

    application = (
        Application.builder()
        .token(TOKEN)
        .build()
    )

    # =========================
    # CUSTOMER CONVERSATION
    # =========================

    customer_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.Regex(
                    r"^(🔧 Сантехник|⚡ Электрик|📱 Телефон таъмири|"
                    r"💻 Компьютер таъмири|🧹 Уй тозалаш|"
                    r"🪑 Мебель таъмири)$"
                ),
                service_selected,
            )
        ],

        states={

            NAME: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_name,
                ),
            ],

            PHONE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_phone,
                ),
            ],

            ADDRESS: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_address,
                ),
            ],

            PROBLEM: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_problem,
                ),
            ],
        },

        fallbacks=[
            CommandHandler("start", start),
            CommandHandler("cancel", cancel_command),
            MessageHandler(
                filters.Regex(MAIN_MENU_PATTERN),
                cancel_to_main,
            ),
        ],

        allow_reentry=False,
    )


    # =========================
    # WORKER CONVERSATION
    # =========================

    worker_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.Regex(r"^👨‍🔧 Уста чақириш$"),
                worker_start,
            )
        ],

        states={

            WORKER_NAME: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_name,
                ),
            ],

            WORKER_PHONE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_phone,
                ),
            ],

            WORKER_SERVICE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_service,
                ),
            ],

            WORKER_AREA: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_area,
                ),
            ],

            WORKER_PRICE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_price,
                ),
            ],
        },

        fallbacks=[
            CommandHandler("start", start),
            CommandHandler("cancel", cancel_command),
            MessageHandler(
                filters.Regex(MAIN_MENU_PATTERN),
                cancel_to_main,
            ),
        ],

        allow_reentry=True,
    )


    # =========================
    # ANNOUNCEMENT CONVERSATION
    # =========================

    announcement_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.Regex(r"^📢 Эълон бериш$"),
                announcement_start,
            )
        ],

        states={

            ANN_NAME: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_name,
                ),
            ],

            ANN_PHONE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_phone,
                ),
            ],

            ANN_SERVICE: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_service,
                ),
            ],

            ANN_ADDRESS: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_address,
                ),
            ],

            ANN_BUDGET: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_budget,
                ),
            ],

            ANN_DETAILS: [
                MessageHandler(
                    filters.Regex(MAIN_MENU_PATTERN),
                    cancel_to_main,
                ),
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_details,
                ),
            ],
        },

        fallbacks=[
            CommandHandler("start", start),
            CommandHandler("cancel", cancel_command),
            MessageHandler(
                filters.Regex(MAIN_MENU_PATTERN),
                cancel_to_main,
            ),
        ],

        allow_reentry=True,
    )


    # =========================
    # COMMANDS
    # =========================

    application.add_handler(
        CommandHandler("start", start)
    )

    application.add_handler(
        CommandHandler("help", help_command)
    )

    application.add_handler(
        CommandHandler("admin", admin)
    )

    application.add_handler(
        CommandHandler("workers", workers_command)
    )

    application.add_handler(
        CommandHandler("orders", orders_command)
    )

    application.add_handler(
        CommandHandler(
            "announcements",
            announcements_command,
        )
    )

    application.add_handler(
        CommandHandler("stats", stats_command)
    )


    # =========================
    # CONVERSATIONS
    # =========================

    application.add_handler(
        customer_conversation
    )

    application.add_handler(
        worker_conversation
    )

    application.add_handler(
        announcement_conversation
    )


    # =========================
    # MENU
    # =========================

    application.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND,
            menu_handler,
        )
    )


    # =========================
    # ERROR
    # =========================

    application.add_error_handler(
        error_handler
    )


    # =========================
    # RENDER WEB SERVICE
    # =========================

    if RENDER_EXTERNAL_URL:

        webhook_url = (
            RENDER_EXTERNAL_URL.rstrip("/")
            + "/telegram"
        )

        logger.info(
            "Starting webhook"
        )

        application.run_webhook(
            listen="0.0.0.0",
            port=PORT,
            url_path="telegram",
            webhook_url=webhook_url,
        )

    else:

        logger.info(
            "Starting polling"
        )

        application.run_polling()


if __name__ == "__main__":
    main()
