import os
import logging
import re
import psycopg

from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ConversationHandler,
    ContextTypes,
    filters,
)

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")
ADMIN_ID = os.getenv("ADMIN_ID")

PORT = int(os.getenv("PORT", "10000"))
RENDER_EXTERNAL_URL = os.getenv("RENDER_EXTERNAL_URL")

if not TOKEN:
    raise RuntimeError("TELEGRAM_BOT_TOKEN is not set")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set")


SERVICES = [
    "🔧 Сантехник",
    "⚡ Электрик",
    "📱 Телефон таъмири",
    "💻 Компьютер таъмири",
    "🧹 Уй тозалаш",
    "🪑 Мебель таъмири",
]


def normalize_service_name(text):
    if not text:
        return ""

    text = text.casefold().strip()

    for emoji in ["🔧", "⚡", "📱", "💻", "🧹", "🪑", "👨‍🔧"]:
        text = text.replace(emoji, "")

    text = text.strip()

    table = str.maketrans({
        "с": "s",
        "а": "a",
        "н": "n",
        "т": "t",
        "е": "e",
        "х": "x",
        "и": "i",
        "к": "k",
        "э": "e",
        "л": "l",
        "е": "e",
        "к": "k",
        "т": "t",
        "р": "r",
        "ф": "f",
        "о": "o",
        "н": "n",
        "т": "t",
        "а": "a",
        "ъ": "",
        "ё": "yo",
        "у": "u",
        "й": "y",
        "м": "m",
        "б": "b",
        "ь": "",
        "ж": "j",
    })

    return text.translate(table)


def service_matches(worker_service, selected_service):
    a = normalize_service_name(worker_service)
    b = normalize_service_name(selected_service)

    if not a or not b:
        return False

    return a == b or a in b or b in a


def get_connection():
    return psycopg.connect(DATABASE_URL)


def init_database():
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS workers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    area TEXT,
                    price TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
            """)

            cur.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    address TEXT,
                    problem TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
            """)

            cur.execute("""
                CREATE TABLE IF NOT EXISTS announcements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    address TEXT,
                    budget TEXT,
                    details TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                """)

        conn.commit()


MAIN_MENU = ReplyKeyboardMarkup(
    [
        ["🔧 Хизматлар"],
        ["👨‍🔧 Уста чақириш"],
        ["📢 Эълон бериш"],
        ["👤 Менинг профилим"],
        ["Алоқа"],
    ],
    resize_keyboard=True,
)


SERVICE_MENU = ReplyKeyboardMarkup(
    [
        ["🔧 Сантехник"],
        ["⚡ Электрик"],
        ["📱 Телефон таъмири"],
        ["💻 Компьютер таъмири"],
        ["🧹 Уй тозалаш"],
        ["🪑 Мебель таъмири"],
        ["⬅️ Орқа"],
    ],
    resize_keyboard=True,
)


WORKER_MENU = ReplyKeyboardMarkup(
    [
        ["👨‍🔧 Уста бўлиб рўйхатдан ўтиш"],
        ["⬅️ Орқа"],
    ],
    resize_keyboard=True,
)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data.clear()

    await update.message.reply_text(
        "🛠 Osh Service ботга хуш келибсиз!\n"
        "Керакли хизматни танланг:",
        reply_markup=MAIN_MENU,
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📖 Ботдан фойдаланиш:\n\n"
        "🔧 Хизматлар — уста қидириш\n"
        "👨‍🔧 Уста чақириш — уста бўлиб рўйхатдан ўтиш\n"
        "📢 Эълон бериш — хизмат учун эълон бериш\n"
        "👤 Менинг профилим — профил маълумотлари"
    )


async def services_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "🔧 Қайси хизмат керак?",
        reply_markup=SERVICE_MENU,
    )


# =========================
# CUSTOMER ORDER
# =========================

CUSTOMER_NAME, CUSTOMER_PHONE, CUSTOMER_ADDRESS, CUSTOMER_PROBLEM = range(4)


async def service_selected(update: Update, context: ContextTypes.DEFAULT_TYPE):
    service = update.message.text.strip()

    if service == "⬅️ Орқа":
        await update.message.reply_text(
            "Асосий меню:",
            reply_markup=MAIN_MENU,
        )
        return ConversationHandler.END

    if service not in SERVICES:
        return ConversationHandler.END

    context.user_data["service"] = service

    workers = []

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT name, service, area, price, phone
                    FROM workers
                    ORDER BY id DESC
                """)

                rows = cur.fetchall()

                for row in rows:
                    if service_matches(row[1], service):
                        workers.append(row)

    except Exception:
        logging.exception("Worker search error")

    if workers:
        text = "👨‍🔧 Мос усталар:\n\n"

        for i, worker in enumerate(workers[:10], 1):
            name, worker_service, area, price, phone = worker

            text += (
                f"#{i} {name}\n"
                f"🔧 Хизмат: {worker_service}\n"
                f"📍 Ҳудуд: {area}\n"
                f"💰 Нархи: {price}\n"
                f"📞 Телефон: {phone}\n\n"
            )

        await update.message.reply_text(text)

    else:
        await update.message.reply_text(
            "😔 Ҳозирча бу хизмат бўйича рўйхатдан ўтган уста топилмади."
        )

    await update.message.reply_text(
        f"Танланган хизмат: {service}\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return CUSTOMER_NAME


async def customer_name(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["name"] = update.message.text.strip()

    await update.message.reply_text("📞 Телефон рақамингизни ёзинг:")

    return CUSTOMER_PHONE


async def customer_phone(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["phone"] = update.message.text.strip()

    await update.message.reply_text("📍 Манзилингизни ёзинг:")

    return CUSTOMER_ADDRESS


async def customer_address(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["address"] = update.message.text.strip()

    await update.message.reply_text("🔧 Муаммони қисқача ёзинг:")

    return CUSTOMER_PROBLEM


async def customer_problem(update: Update, context: ContextTypes.DEFAULT_TYPE):
    problem = update.message.text.strip()

    user_id = update.effective_user.id

    name = context.user_data.get("name", "")
    phone = context.user_data.get("phone", "")
    service = context.user_data.get("service", "")
    address = context.user_data.get("address", "")

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO orders
                    (telegram_id, name, phone, service, address, problem)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        user_id,
                        name,
                        phone,
                        service,
                        address,
                        problem,
                    ),
                )

            conn.commit()

    except Exception:
        logging.exception("Order save error")

        await update.message.reply_text(
            "❌ Буюртмани сақлашда хатолик юз берди. Илтимос, кейинроқ қайта уриниб кўринг.",
            reply_markup=MAIN_MENU,
        )

        context.user_data.clear()
        return ConversationHandler.END

    order_text = (
        "🔔 ЯНГИ БУЮРТМА!\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Манзил: {address}\n"
        f"📝 Муаммо: {problem}"
    )

    if ADMIN_ID:
        try:
            await context.bot.send_message(
                chat_id=int(ADMIN_ID),
                text=order_text,
            )
        except Exception:
            logging.exception("Admin notification error")

    await update.message.reply_text(
        "✅ Буюртмангиз қабул қилинди!\n"
        "Усталарга хабар берилади.",
        reply_markup=MAIN_MENU,
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# WORKER REGISTRATION
# =========================

WORKER_NAME, WORKER_PHONE, WORKER_SERVICE, WORKER_AREA, WORKER_PRICE = range(5, 10)


async def worker_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👨‍🔧 Уста бўлсангиз, рўйхатдан ўтишингиз мумкин.",
        reply_markup=WORKER_MENU,
    )


async def worker_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👤 Исм ва фамилиянгизни ёзинг:")

    return WORKER_NAME


async def worker_name(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["worker_name"] = update.message.text.strip()

    await update.message.reply_text("📞 Телефон рақамингизни ёзинг:")

    return WORKER_PHONE


async def worker_phone(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["worker_phone"] = update.message.text.strip()

    await update.message.reply_text(
        "🔧 Қайси хизматни кўрсатасиз?\n"
        "Масалан: Сантехник, Электрик"
    )

    return WORKER_SERVICE


async def worker_service(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["worker_service"] = update.message.text.strip()

    await update.message.reply_text(
        "📍 Қайси ҳудудда ишлайсиз?"
    )

    return WORKER_AREA


async def worker_area(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["worker_area"] = update.message.text.strip()

    await update.message.reply_text(
        "💰 Хизмат нархини ёзинг:"
    )

    return WORKER_PRICE


async def worker_price(update: Update, context: ContextTypes.DEFAULT_TYPE):
    price = update.message.text.strip()

    user_id = update.effective_user.id

    name = context.user_data.get("worker_name", "")
    phone = context.user_data.get("worker_phone", "")
    service = context.user_data.get("worker_service", "")
    area = context.user_data.get("worker_area", "")

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO workers
                    (telegram_id, name, phone, service, area, price)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        user_id,
                        name,
                        phone,
                        service,
                        area,
                        price,
                    ),
                )

            conn.commit()

    except Exception:
        logging.exception("Worker save error")

        await update.message.reply_text(
            "❌ Маълумотни сақлашда хатолик юз берди.",
            reply_markup=MAIN_MENU,
        )

        context.user_data.clear()
        return ConversationHandler.END

    worker_text = (
        "👨‍🔧 ЯНГИ УСТА РЎЙХАТДАН ЎТДИ!\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Ҳудуд: {area}\n"
        f"💰 Нархи: {price}"
    )

    if ADMIN_ID:
        try:
            await context.bot.send_message(
                chat_id=int(ADMIN_ID),
                text=worker_text,
            )
        except Exception:
            logging.exception("Admin worker notification error")

    await update.message.reply_text(
        "✅ Сиз уста сифатида муваффақиятли рўйхатдан ўтдингиз!",
        reply_markup=MAIN_MENU,
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# ANNOUNCEMENT
# =========================

ANN_NAME, ANN_PHONE, ANN_SERVICE, ANN_ADDRESS, ANN_BUDGET, ANN_DETAILS = range(
    10, 16
)


async def announcement_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👤 Исмингизни ёзинг:")

    return ANN_NAME


async def ann_name(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["ann_name"] = update.message.text.strip()

    await update.message.reply_text("📞 Телефон рақамингизни ёзинг:")

    return ANN_PHONE


async def ann_phone(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["ann_phone"] = update.message.text.strip()

    await update.message.reply_text("🔧 Қайси хизмат керак?")

    return ANN_SERVICE


async def ann_service(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["ann_service"] = update.message.text.strip()

    await update.message.reply_text("📍 Манзилни ёзинг:")

    return ANN_ADDRESS


async def ann_address(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["ann_address"] = update.message.text.strip()

    await update.message.reply_text("💰 Бюджетингизни ёзинг:")

    return ANN_BUDGET


async def ann_budget(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["ann_budget"] = update.message.text.strip()

    await update.message.reply_text("📝 Қўшимча маълумот ёзинг:")

    return ANN_DETAILS


async def ann_details(update: Update, context: ContextTypes.DEFAULT_TYPE):
    details = update.message.text.strip()

    user_id = update.effective_user.id

    name = context.user_data.get("ann_name", "")
    phone = context.user_data.get("ann_phone", "")
    service = context.user_data.get("ann_service", "")
    address = context.user_data.get("ann_address", "")
    budget = context.user_data.get("ann_budget", "")

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO announcements
                    (telegram_id, name, phone, service, address, budget, details)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        user_id,
                        name,
                        phone,
                        service,
                        address,
                        budget,
                        details,
                    ),
                )

            conn.commit()

    except Exception:
        logging.exception("Announcement save error")

        await update.message.reply_text(
            "❌ Эълонни сақлашда хатолик юз берди.",
            reply_markup=MAIN_MENU,
        )

        context.user_data.clear()
        return ConversationHandler.END

    announcement_text = (
        "📢 ЯНГИ ЭЪЛОН!\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Манзил: {address}\n"
        f"💰 Бюджет: {budget}\n"
        f"📝 Маълумот: {details}"
    )

    if ADMIN_ID:
        try:
            await context.bot.send_message(
                chat_id=int(ADMIN_ID),
                text=announcement_text,
            )
        except Exception:
            logging.exception("Admin announcement notification error")

    await update.message.reply_text(
        "✅ Эълонингиз қабул қилинди!",
        reply_markup=MAIN_MENU,
    )

    context.user_data.clear()

    return ConversationHandler.END


# =========================
# PROFILE
# =========================

async def my_profile(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT name, phone, service, area, price
                    FROM workers
                    WHERE telegram_id = %s
                    ORDER BY id DESC
                    LIMIT 1
                    """,
                    (user_id,),
                )

                worker = cur.fetchone()

        if worker:
            name, phone, service, area, price = worker

            await update.message.reply_text(
                "👤 Менинг профилим\n\n"
                f"Исм: {name}\n"
                f"Телефон: {phone}\n"
                f"Хизмат: {service}\n"
                f"Ҳудуд: {area}\n"
                f"Нарх: {price}"
            )
        else:
            await update.message.reply_text(
                "👤 Сиз ҳали уста сифатида рўйхатдан ўтмагансиз."
            )

    except Exception:
        logging.exception("Profile error")

        await update.message.reply_text(
            "❌ Профилни олишда хатолик юз берди."
        )


# =========================
# ADMIN
# =========================

async def admin_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not ADMIN_ID:
        return

    if str(update.effective_user.id) != str(ADMIN_ID):
        await update.message.reply_text("⛔ Рухсат йўқ.")
        return

    await update.message.reply_text(
        "🔐 Админ панель\n\n"
        "👨‍🔧 Усталар — /workers\n"
        "📢 Эълонлар — /announcements\n"
        "🔔 Буюртмалар — /orders\n"
        "📊 Статистика — /stats"
    )


async def admin_workers(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if str(update.effective_user.id) != str(ADMIN_ID):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT name, service, area, price, phone
                FROM workers
                ORDER BY id DESC
                LIMIT 30
            """)

            rows = cur.fetchall()

    if not rows:
        await update.message.reply_text("👨‍🔧 Ҳозирча усталар йўқ.")
        return

    text = "👨‍🔧 Усталар:\n\n"

    for i, row in enumerate(rows, 1):
        name, service, area, price, phone = row

        text += (
            f"#{i} {name}\n"
            f"🔧 {service}\n"
            f"📍 {area}\n"
            f"💰 {price}\n"
            f"📞 {phone}\n\n"
        )

    await update.message.reply_text(text)


async def admin_orders(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if str(update.effective_user.id) != str(ADMIN_ID):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT name, service, address, problem, created_at
                FROM orders
                ORDER BY id DESC
                LIMIT 30
            """)

            rows = cur.fetchall()

    if not rows:
        await update.message.reply_text("🔔 Ҳозирча буюртмалар йўқ.")
        return

    text = "🔔 Буюртмалар:\n\n"

    for row in rows:
        name, service, address, problem, created_at = row

        text += (
            f"👤 {name}\n"
            f"🔧 {service}\n"
            f"📍 {address}\n"
            f"📝 {problem}\n"
            f"🕐 {created_at}\n\n"
        )

    await update.message.reply_text(text)


async def admin_announcements(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if str(update.effective_user.id) != str(ADMIN_ID):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT name, service, address, budget, details, created_at
                FROM announcements
                ORDER BY id DESC
                LIMIT 30
            """)

            rows = cur.fetchall()

    if not rows:
        await update.message.reply_text("📢 Ҳозирча эълонлар йўқ.")
        return

    text = "📢 Эълонлар:\n\n"

    for row in rows:
        name, service, address, budget, details, created_at = row

        text += (
            f"👤 {name}\n"
            f"🔧 {service}\n"
            f"📍 {address}\n"
            f"💰 {budget}\n"
            f"📝 {details}\n"
            f"🕐 {created_at}\n\n"
        )

    await update.message.reply_text(text)


async def admin_stats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if str(update.effective_user.id) != str(ADMIN_ID):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM workers")
            workers_count = cur.fetchone()[0]

            cur.execute("SELECT COUNT(*) FROM orders")
            orders_count = cur.fetchone()[0]

            cur.execute("SELECT COUNT(*) FROM announcements")
            announcements_count = cur.fetchone()[0]

    total = workers_count + orders_count + announcements_count

    await update.message.reply_text(
        "📊 Статистика\n\n"
        f"👨‍🔧 Усталар: {workers_count}\n"
        f"🔔 Буюртмалар: {orders_count}\n"
        f"📢 Эълонлар: {announcements_count}\n"
        f"📊 Жами: {total}"
    )


async def contact(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📞 Osh Service\n\n"
        "Хизматлар бўйича бот орқали мурожаат қилинг."
    )


async def back_to_main(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Асосий меню:",
        reply_markup=MAIN_MENU,
    )


async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE):
    logging.exception(
        "Unhandled error:",
        exc_info=context.error,
    )


def main():
    init_database()

    application = Application.builder().token(TOKEN).build()

    customer_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.TEXT & filters.Regex(
                    r"^(?:"
                    + "|".join(re.escape(service) for service in SERVICES)
                    + r")$"
                ),
                service_selected,
            )
        ],
        states={
            CUSTOMER_NAME: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, customer_name)
            ],
            CUSTOMER_PHONE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, customer_phone)
            ],
            CUSTOMER_ADDRESS: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, customer_address)
            ],
            CUSTOMER_PROBLEM: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, customer_problem)
            ],
        },
        fallbacks=[],
    )

    worker_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.Regex(r"^👨‍🔧 Уста бўлиб рўйхатдан ўтиш$"),
                worker_start,
            )
        ],
        states={
            WORKER_NAME: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, worker_name)
            ],
            WORKER_PHONE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, worker_phone)
            ],
            WORKER_SERVICE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, worker_service)
            ],
            WORKER_AREA: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, worker_area)
            ],
            WORKER_PRICE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, worker_price)
            ],
        },
        fallbacks=[],
    )

    announcement_conversation = ConversationHandler(
        entry_points=[
            MessageHandler(
                filters.Regex(r"^📢 Эълон бериш$"),
                announcement_start,
            )
        ],
        states={
            ANN_NAME: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_name)
            ],
            ANN_PHONE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_phone)
            ],
            ANN_SERVICE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_service)
            ],
            ANN_ADDRESS: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_address)
            ],
            ANN_BUDGET: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_budget)
            ],
            ANN_DETAILS: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, ann_details)
            ],
        },
        fallbacks=[],
    )

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("admin", admin_command))
    application.add_handler(CommandHandler("workers", admin_workers))
    application.add_handler(CommandHandler("orders", admin_orders))
    application.add_handler(CommandHandler("announcements", admin_announcements))
    application.add_handler(CommandHandler("stats", admin_stats))

    application.add_handler(customer_conversation)
    application.add_handler(worker_conversation)
    application.add_handler(announcement_conversation)

    application.add_handler(
        MessageHandler(
            filters.Regex(r"^🔧 Хизматлар$"),
            services_menu,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(r"^👨‍🔧 Уста чақириш$"),
            worker_menu,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(r"^👤 Менинг профилим$"),
            my_profile,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(r"^Алоқа$"),
            contact,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(r"^⬅️ Орқа$"),
            back_to_main,
        )
    )

    application.add_error_handler(error_handler)

    if RENDER_EXTERNAL_URL:
        webhook_url = RENDER_EXTERNAL_URL.rstrip("/") + "/telegram"

        logging.info("Starting webhook on port %s", PORT)

        application.run_webhook(
            listen="0.0.0.0",
            port=PORT,
            url_path="telegram",
            webhook_url=webhook_url,
        )
    else:
        logging.info("Starting polling")

        application.run_polling()


if __name__ == "__main__":
    main()
