import os
import re
import logging

import psycopg

from telegram import (
    Update,
    ReplyKeyboardMarkup,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ConversationHandler,
    ContextTypes,
    filters,
)


# ============================================================
# LOGGING
# ============================================================

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

logger = logging.getLogger(__name__)


# ============================================================
# ENVIRONMENT
# ============================================================

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")

ADMIN_ID = (
    int(os.getenv("ADMIN_ID", "0"))
    if os.getenv("ADMIN_ID")
    else 0
)

PORT = int(os.getenv("PORT", "10000"))

RENDER_EXTERNAL_URL = (
    os.getenv("RENDER_EXTERNAL_URL", "").rstrip("/")
)


if not TOKEN:
    raise RuntimeError("TELEGRAM_BOT_TOKEN topilmadi")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL topilmadi")


# ============================================================
# CONVERSATION STATES
# ============================================================

WORKER_NAME = 0
WORKER_PHONE = 1
WORKER_SERVICE = 2
WORKER_AREA = 3
WORKER_PRICE = 4

ORDER_NAME = 5
ORDER_PHONE = 6
ORDER_ADDRESS = 7
ORDER_PROBLEM = 8

ANN_NAME = 9
ANN_PHONE = 10
ANN_SERVICE = 11
ANN_ADDRESS = 12
ANN_BUDGET = 13
ANN_DETAILS = 14

EDIT_WORKER_NAME = 20
EDIT_WORKER_PHONE = 21
EDIT_WORKER_SERVICE = 22
EDIT_WORKER_AREA = 23
EDIT_WORKER_PRICE = 24


# ============================================================
# SERVICES
# ============================================================

SERVICES = [
    "🔧 Сантехник",
    "⚡ Электрик",
    "📱 Телефон таъмири",
    "💻 Компьютер таъмири",
    "🧹 Уй тозалаш",
    "🪑 Мебель таъмири",
]


# ============================================================
# DATABASE
# ============================================================

def get_connection():
    return psycopg.connect(
        DATABASE_URL,
        connect_timeout=10,
    )


def init_database():
    with get_connection() as conn:
        with conn.cursor() as cur:

            # ------------------------------------------------
            # WORKERS
            # ------------------------------------------------

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS workers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    area TEXT,
                    price TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
                """
            )

            # ------------------------------------------------
            # ORDERS
            # ------------------------------------------------

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    address TEXT,
                    problem TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
                """
            )

            # ------------------------------------------------
            # ANNOUNCEMENTS
            # ------------------------------------------------

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS announcements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_id BIGINT,
                    name TEXT,
                    phone TEXT,
                    service TEXT,
                    address TEXT,
                    budget TEXT,
                    details TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
                """
            )

            # ------------------------------------------------
            # WORKER ACTIVE STATUS
            # ------------------------------------------------

            cur.execute(
                """
                ALTER TABLE workers
                ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE
                """
            )

            cur.execute(
                """
                UPDATE workers
                SET is_active = TRUE
                WHERE is_active IS NULL
                """
            )

            # ------------------------------------------------
            # ORDER STATUS
            # ------------------------------------------------

            cur.execute(
                """
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'new'
                """
            )

            cur.execute(
                """
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS accepted_worker_id BIGINT
                """
            )

            cur.execute(
                """
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS accepted_worker_name TEXT
                """
            )

            cur.execute(
                """
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ
                """
            )

            cur.execute(
                """
                UPDATE orders
                SET status = 'new'
                WHERE status IS NULL
                """
            )

        conn.commit()

    logger.info("Database initialized successfully")


# ============================================================
# SERVICE NORMALIZATION
# ============================================================

def normalize_service_name(text):
    if not text:
        return ""

    text = str(text).casefold()

    # Remove emojis
    text = re.sub(
        r"[🔧⚡📱💻🧹🪑👨‍🔧]",
        "",
        text,
    )

    replacements = {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "yo",
        "ж": "j",
        "з": "z",
        "и": "i",
        "й": "y",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "x",
        "ц": "ts",
        "ч": "ch",
        "ш": "sh",
        "щ": "sh",
        "ъ": "",
        "ы": "y",
        "ь": "",
        "э": "e",
        "ю": "yu",
        "я": "ya",
        "қ": "q",
        "ғ": "g",
        "ҳ": "h",
        "ў": "o",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text,
    )

    text = re.sub(
        r"\s+",
        " ",
        text,
    )

    return text.strip()


def canonical_service(text):
    normalized = normalize_service_name(text)

    if not normalized:
        return ""

    # Computer
    if (
        "kompyuter" in normalized
        or "komyuter" in normalized
        or "komputer" in normalized
    ):
        return "kompyuter"

    # Plumbing
    if (
        "santexnik" in normalized
        or "santehnik" in normalized
    ):
        return "santexnik"

    # Electrician
    if "elektrik" in normalized:
        return "elektrik"

    # Phone
    if "telefon" in normalized:
        return "telefon"

    # Cleaning
    if (
        "uy tozalash" in normalized
        or "tozalash" in normalized
    ):
        return "tozalash"

    # Furniture
    if "mebel" in normalized:
        return "mebel"

    return normalized


def service_matches(
    selected_service,
    worker_services,
):
    selected = canonical_service(
        selected_service
    )

    if not selected or not worker_services:
        return False

    parts = re.split(
        r"[,;/\n]+",
        str(worker_services),
    )

    for part in parts:
        if canonical_service(part) == selected:
            return True

    return False


# ============================================================
# KEYBOARDS
# ============================================================

def main_keyboard():
    return ReplyKeyboardMarkup(
        [
            ["🔧 Хизматлар", "👨‍🔧 Уста чақириш"],
            ["📢 Эълон бериш", "Алоқа"],
            ["👤 Менинг профилим"],
        ],
        resize_keyboard=True,
    )


def services_keyboard():
    return ReplyKeyboardMarkup(
        [
            [SERVICES[0], SERVICES[1]],
            [SERVICES[2], SERVICES[3]],
            [SERVICES[4], SERVICES[5]],
            ["⬅️ Бош меню"],
        ],
        resize_keyboard=True,
    )


def worker_services_keyboard():
    return ReplyKeyboardMarkup(
        [
            [SERVICES[0], SERVICES[1]],
            [SERVICES[2], SERVICES[3]],
            [SERVICES[4], SERVICES[5]],
        ],
        resize_keyboard=True,
    )


# ============================================================
# START
# ============================================================

async def start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    context.user_data.clear()

    await update.message.reply_text(
        "🛠 Osh Service ботга хуш келибсиз!\n\n"
        "Керакли хизматни танланг:",
        reply_markup=main_keyboard(),
    )


# ============================================================
# HELP
# ============================================================

async def help_command(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    await update.message.reply_text(
        "ℹ️ Osh Service\n\n"
        "🔧 Хизматлар — мавжуд хизматлар\n"
        "👨‍🔧 Уста чақириш — уста бўлиб рўйхатдан ўтиш\n"
        "📢 Эълон бериш — хизмат/иш ҳақида эълон\n"
        "👤 Менинг профилим — уста профили\n"
        "Алоқа — администратор билан боғланиш\n\n"
        "/workers — усталар\n"
        "/orders — буюртмалар\n"
        "/stats — статистика"
    )


# ============================================================
# SERVICES
# ============================================================

async def show_services(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    await update.message.reply_text(
        "🔧 Хизматлар:",
        reply_markup=services_keyboard(),
    )


# ============================================================
# WORKER MENU
# ============================================================

async def worker_menu(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    keyboard = ReplyKeyboardMarkup(
        [
            ["👨‍🔧 Уста бўлиб рўйхатдан ўтиш"],
            ["👤 Менинг профилим"],
            ["⬅️ Бош меню"],
        ],
        resize_keyboard=True,
    )

    await update.message.reply_text(
        "👨‍🔧 Уста бўлими:",
        reply_markup=keyboard,
    )


# ============================================================
# WORKER REGISTRATION
# ============================================================

async def worker_register_start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    context.user_data.clear()

    await update.message.reply_text(
        "👨‍🔧 Уста бўлиб рўйхатдан ўтиш\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return WORKER_NAME


async def worker_name(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    name = update.message.text.strip()

    if not name:
        await update.message.reply_text(
            "❗ Исмни бўш қолдирманг."
        )
        return WORKER_NAME

    context.user_data["worker_name"] = name

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return WORKER_PHONE


async def worker_phone(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    phone = update.message.text.strip()

    if len(re.sub(r"\D", "", phone)) < 7:
        await update.message.reply_text(
            "❗ Телефон рақами нотўғри. Қайта ёзинг:"
        )
        return WORKER_PHONE

    context.user_data["worker_phone"] = phone

    await update.message.reply_text(
        "🔧 Қайси хизматни кўрсатасиз?",
        reply_markup=worker_services_keyboard(),
    )

    return WORKER_SERVICE


async def worker_service(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    service = update.message.text.strip()

    if not service:
        await update.message.reply_text(
            "❗ Хизматни киритинг."
        )
        return WORKER_SERVICE

    context.user_data["worker_service"] = service

    await update.message.reply_text(
        "📍 Ҳудудингизни ёзинг:"
    )

    return WORKER_AREA


async def worker_area(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    area = update.message.text.strip()

    if not area:
        await update.message.reply_text(
            "❗ Ҳудудни бўш қолдирманг."
        )
        return WORKER_AREA

    context.user_data["worker_area"] = area

    await update.message.reply_text(
        "💰 Хизмат нархингизни ёзинг:"
    )

    return WORKER_PRICE


async def worker_price(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    price = update.message.text.strip()

    if not price:
        await update.message.reply_text(
            "❗ Нарҳни киритинг."
        )
        return WORKER_PRICE

    context.user_data["worker_price"] = price

    data = context.user_data
    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                SELECT id
                FROM workers
                WHERE telegram_id=%s
                ORDER BY id DESC
                LIMIT 1
                """,
                (user.id,),
            )

            existing = cur.fetchone()

            if existing:

                cur.execute(
                    """
                    UPDATE workers
                    SET
                        name=%s,
                        phone=%s,
                        service=%s,
                        area=%s,
                        price=%s,
                        is_active=TRUE
                    WHERE id=%s
                    """,
                    (
                        data["worker_name"],
                        data["worker_phone"],
                        data["worker_service"],
                        data["worker_area"],
                        data["worker_price"],
                        existing[0],
                    ),
                )

            else:

                cur.execute(
                    """
                    INSERT INTO workers
                    (
                        telegram_id,
                        name,
                        phone,
                        service,
                        area,
                        price,
                        is_active
                    )
                    VALUES (%s,%s,%s,%s,%s,%s,TRUE)
                    """,
                    (
                        user.id,
                        data["worker_name"],
                        data["worker_phone"],
                        data["worker_service"],
                        data["worker_area"],
                        data["worker_price"],
                    ),
                )

        conn.commit()

    await update.message.reply_text(
        "✅ Уста профилингиз сақланди!\n\n"
        f"👤 Исм: {data['worker_name']}\n"
        f"📞 Телефон: {data['worker_phone']}\n"
        f"🔧 Хизмат: {data['worker_service']}\n"
        f"📍 Ҳудуд: {data['worker_area']}\n"
        f"💰 Нархи: {data['worker_price']}\n"
        "🟢 Ҳолат: Фаол",
        reply_markup=main_keyboard(),
    )

    context.user_data.clear()

    return ConversationHandler.END


# ============================================================
# CUSTOMER ORDER
# ============================================================

async def order_from_service(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    service = update.message.text.strip()

    if service not in SERVICES:
        await update.message.reply_text(
            "❗ Хизматни тугмалардан танланг:",
            reply_markup=services_keyboard(),
        )
        return ORDER_NAME

    # IMPORTANT:
    # Do NOT use context.user_data.clear()
    # because the conversation can lose order data.
    context.user_data.pop(
        "order_data",
        None,
    )

    context.user_data["order_data"] = {
        "service": service,
    }

    await update.message.reply_text(
        f"✅ Хизмат: {service}\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return ORDER_NAME


async def customer_name(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    name = update.message.text.strip()

    if not name:
        await update.message.reply_text(
            "❗ Исмни бўш қолдирманг."
        )
        return ORDER_NAME

    order_data = context.user_data.get(
        "order_data"
    )

    if not order_data:
        await update.message.reply_text(
            "⚠️ Буюртма жараёни бузилди.\n\n"
            "Илтимос, хизматни қайта танланг.",
            reply_markup=services_keyboard(),
        )
        return ConversationHandler.END

    order_data["name"] = name

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return ORDER_PHONE


async def customer_phone(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    phone = update.message.text.strip()

    if len(re.sub(r"\D", "", phone)) < 7:
        await update.message.reply_text(
            "❗ Телефон рақами нотўғри. Қайта ёзинг:"
        )
        return ORDER_PHONE

    order_data = context.user_data.get(
        "order_data"
    )

    if not order_data:
        await update.message.reply_text(
            "⚠️ Буюртма жараёни бузилди.\n\n"
            "Илтимос, хизматни қайта танланг.",
            reply_markup=services_keyboard(),
        )
        return ConversationHandler.END

    order_data["phone"] = phone

    await update.message.reply_text(
        "📍 Манзилингизни ёзинг:"
    )

    return ORDER_ADDRESS


async def customer_address(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    address = update.message.text.strip()

    if not address:
        await update.message.reply_text(
            "❗ Манзилни бўш қолдирманг."
        )
        return ORDER_ADDRESS

    order_data = context.user_data.get(
        "order_data"
    )

    if not order_data:
        await update.message.reply_text(
            "⚠️ Буюртма жараёни бузилди.\n\n"
            "Илтимос, хизматни қайта танланг.",
            reply_markup=services_keyboard(),
        )
        return ConversationHandler.END

    order_data["address"] = address

    await update.message.reply_text(
        "📝 Муаммони қисқача ёзинг:"
    )

    return ORDER_PROBLEM


async def customer_problem(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    problem = update.message.text.strip()

    if not problem:
        await update.message.reply_text(
            "❗ Муаммони ёзинг."
        )
        return ORDER_PROBLEM

    order_data = context.user_data.get(
        "order_data"
    )

    if not order_data:
        await update.message.reply_text(
            "⚠️ Буюртма маълумотлари топилмади.\n\n"
            "Илтимос, хизматни қайта танлаб, "
            "буюртмани бошидан беринг.",
            reply_markup=services_keyboard(),
        )
        return ConversationHandler.END

    required = [
        "service",
        "name",
        "phone",
        "address",
    ]

    if not all(
        order_data.get(key)
        for key in required
    ):
        context.user_data.pop(
            "order_data",
            None,
        )

        await update.message.reply_text(
            "⚠️ Буюртма маълумотлари тўлиқ эмас.\n\n"
            "Илтимос, буюртмани қайта беринг.",
            reply_markup=services_keyboard(),
        )

        return ConversationHandler.END

    user = update.effective_user

    service = order_data["service"]
    customer_name_value = order_data["name"]
    customer_phone_value = order_data["phone"]
    customer_address_value = order_data["address"]

    # --------------------------------------------------------
    # SAVE ORDER
    # --------------------------------------------------------

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                INSERT INTO orders
                (
                    telegram_id,
                    name,
                    phone,
                    service,
                    address,
                    problem,
                    status
                )
                VALUES (%s,%s,%s,%s,%s,%s,'new')
                RETURNING id
                """,
                (
                    user.id,
                    customer_name_value,
                    customer_phone_value,
                    service,
                    customer_address_value,
                    problem,
                ),
            )

            order_id = cur.fetchone()[0]

            # ONLY ACTIVE WORKERS
            cur.execute(
                """
                SELECT
                    telegram_id,
                    name,
                    service,
                    area,
                    price
                FROM workers
                WHERE COALESCE(is_active, TRUE) = TRUE
                  AND telegram_id IS NOT NULL
                ORDER BY id DESC
                """
            )

            workers = cur.fetchall()

        conn.commit()

    # --------------------------------------------------------
    # NOTIFY MATCHING WORKERS
    # --------------------------------------------------------

    message = (
        f"🔔 ЯНГИ БУЮРТМА #{order_id}\n\n"
        f"🔧 Хизмат: {service}\n"
        f"👤 Мижоз: {customer_name_value}\n"
        f"📞 Телефон: {customer_phone_value}\n"
        f"📍 Манзил: {customer_address_value}\n"
        f"📝 Муаммо: {problem}\n\n"
        "Буюртмани олиш учун тугмани босинг."
    )

    sent_ids = set()
    notified_count = 0

    for (
        worker_telegram_id,
        worker_name,
        worker_service,
        worker_area,
        worker_price,
    ) in workers:

        if not worker_telegram_id:
            continue

        if worker_telegram_id in sent_ids:
            continue

        if not service_matches(
            service,
            worker_service,
        ):
            logger.info(
                "Order #%s: service mismatch. "
                "Worker=%s, service=%s, requested=%s",
                order_id,
                worker_name,
                worker_service,
                service,
            )
            continue

        sent_ids.add(
            worker_telegram_id
        )

        keyboard = InlineKeyboardMarkup(
            [
                [
                    InlineKeyboardButton(
                        "✅ Буюртмани оламан",
                        callback_data=(
                            f"accept_order:{order_id}"
                        ),
                    )
                ]
            ]
        )

        try:

            await context.bot.send_message(
                chat_id=worker_telegram_id,
                text=message,
                reply_markup=keyboard,
            )

            notified_count += 1

            logger.info(
                "✅ Order #%s sent to worker "
                "%s (%s)",
                order_id,
                worker_name,
                worker_telegram_id,
            )

        except Exception as exc:

            logger.exception(
                "❌ Worker notification failed "
                "for %s (%s): %s",
                worker_name,
                worker_telegram_id,
                exc,
            )

    # --------------------------------------------------------
    # CUSTOMER CONFIRMATION
    # --------------------------------------------------------

    if notified_count > 0:

        confirmation = (
            f"✅ Буюртмангиз қабул қилинди!\n\n"
            f"Буюртма рақами: #{order_id}\n"
            f"👨‍🔧 {notified_count} та фаол "
            f"устага хабар юборилди.\n\n"
            "Уста қабул қилса, сизга "
            "унинг маълумотлари келади."
        )

    else:

        confirmation = (
            f"✅ Буюртмангиз қабул қилинди!\n\n"
            f"Буюртма рақами: #{order_id}\n\n"
            "⚠️ Ҳозирча бу хизмат бўйича "
            "фаол уста топилмади."
        )

    await update.message.reply_text(
        confirmation,
        reply_markup=main_keyboard(),
    )

    context.user_data.pop(
        "order_data",
        None,
    )

    return ConversationHandler.END


# ============================================================
# ACCEPT ORDER
# ============================================================

async def accept_order_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    query = update.callback_query

    await query.answer()

    user = update.effective_user

    try:
        order_id = int(
            query.data.split(":", 1)[1]
        )
    except Exception:

        await query.message.reply_text(
            "❗ Буюртма рақами нотўғри."
        )

        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            # ------------------------------------------------
            # FIND WORKER
            # ------------------------------------------------

            cur.execute(
                """
                SELECT
                    id,
                    name,
                    phone,
                    is_active
                FROM workers
                WHERE telegram_id=%s
                ORDER BY id DESC
                LIMIT 1
                """,
                (user.id,),
            )

            worker = cur.fetchone()

            if not worker:

                await query.message.reply_text(
                    "❗ Сизда уста профили "
                    "мавжуд эмас."
                )

                return

            if worker[3] is False:

                await query.message.reply_text(
                    "🔴 Профилингиз нофаол.\n\n"
                    "Янги буюртмаларни "
                    "қабул қила олмайсиз."
                )

                return

            worker_id = worker[0]
            worker_name = worker[1]
            worker_phone = worker[2]

            # ------------------------------------------------
            # ACCEPT ONLY NEW ORDER
            # ------------------------------------------------

            cur.execute(
                """
                UPDATE orders
                SET
                    status='accepted',
                    accepted_worker_id=%s,
                    accepted_worker_name=%s,
                    accepted_at=NOW()
                WHERE id=%s
                  AND status='new'
                RETURNING
                    telegram_id,
                    name,
                    phone,
                    service,
                    address,
                    problem
                """,
                (
                    worker_id,
                    worker_name,
                    order_id,
                ),
            )

            order = cur.fetchone()

        conn.commit()

    # --------------------------------------------------------
    # ORDER ALREADY ACCEPTED
    # --------------------------------------------------------

    if not order:

        await query.message.reply_text(
            "⚠️ Бу буюртма аллақачон "
            "бошқа уста томонидан қабул "
            "қилинган."
        )

        try:
            await query.edit_message_reply_markup(
                reply_markup=None
            )
        except Exception:
            pass

        return

    # --------------------------------------------------------
    # ORDER DATA
    # --------------------------------------------------------

    customer_id = order[0]
    customer_name = order[1]
    customer_phone = order[2]
    service = order[3]
    address = order[4]
    problem = order[5]

    # Remove accept button
    try:

        await query.edit_message_reply_markup(
            reply_markup=None
        )

    except Exception:
        pass

    # --------------------------------------------------------
    # WORKER CONFIRMATION
    # --------------------------------------------------------

    await query.message.reply_text(
        f"✅ Буюртма #{order_id} "
        "сиз томонингиздан қабул қилинди!\n\n"
        f"👤 Мижоз: {customer_name}\n"
        f"📞 Мижоз телефони: {customer_phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Манзил: {address}\n"
        f"📝 Муаммо: {problem}"
    )

    # --------------------------------------------------------
    # CUSTOMER NOTIFICATION
    # --------------------------------------------------------

    try:

        await context.bot.send_message(
            chat_id=customer_id,
            text=(
                "✅ БУЮРТМАНГИЗНИ УСТА ҚАБУЛ ҚИЛДИ!\n\n"
                f"👨‍🔧 Уста: {worker_name}\n"
                f"📞 Устанинг рақами: {worker_phone}\n\n"
                f"🔧 Хизмат: {service}\n"
                f"📍 Манзил: {address}"
            ),
        )

        logger.info(
            "✅ Customer %s notified about "
            "accepted order #%s",
            customer_id,
            order_id,
        )

    except Exception as exc:

        logger.exception(
            "❌ Customer notification failed: %s",
            exc,
        )


# ============================================================
# MY PROFILE
# ============================================================

async def my_profile(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                SELECT
                    id,
                    name,
                    phone,
                    service,
                    area,
                    price,
                    created_at,
                    COALESCE(is_active, TRUE)
                FROM workers
                WHERE telegram_id=%s
                ORDER BY id DESC
                LIMIT 1
                """,
                (user.id,),
            )

            worker = cur.fetchone()

    if not worker:

        if update.callback_query:

            await update.callback_query.message.reply_text(
                "❗ Сиз ҳали уста сифатида "
                "рўйхатдан ўтмагансиз.",
                reply_markup=main_keyboard(),
            )

        else:

            await update.message.reply_text(
                "❗ Сиз ҳали уста сифатида "
                "рўйхатдан ўтмагансиз.",
                reply_markup=main_keyboard(),
            )

        return

    (
        worker_id,
        name,
        phone,
        service,
        area,
        price,
        created_at,
        is_active,
    ) = worker

    status = (
        "🟢 Фаол"
        if is_active
        else "🔴 Нофаол"
    )

    toggle_text = (
        "🔴 Нофаол қилиш"
        if is_active
        else "🟢 Фаол қилиш"
    )

    keyboard = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "✏️ Профилни таҳрирлаш",
                    callback_data="edit_profile",
                )
            ],
            [
                InlineKeyboardButton(
                    toggle_text,
                    callback_data=(
                        f"toggle_worker:{worker_id}"
                    ),
                )
            ],
            [
                InlineKeyboardButton(
                    "⬅️ Бош меню",
                    callback_data="profile_main_menu",
                )
            ],
        ]
    )

    text = (
        "👤 МЕНИНГ ПРОФИЛИМ\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Ҳудуд: {area}\n"
        f"💰 Нархи: {price}\n"
        f"📌 Ҳолат: {status}\n"
        f"🕐 Рўйхатдан ўтган: {created_at}\n"
    )

    if update.callback_query:

        await update.callback_query.edit_message_text(
            text,
            reply_markup=keyboard,
        )

    else:

        await update.message.reply_text(
            text,
            reply_markup=keyboard,
        )


# ============================================================
# EDIT PROFILE
# ============================================================

async def start_edit_profile(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    query = update.callback_query

    await query.answer()

    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                SELECT
                    name,
                    phone,
                    service,
                    area,
                    price
                FROM workers
                WHERE telegram_id=%s
                ORDER BY id DESC
                LIMIT 1
                """,
                (user.id,),
            )

            worker = cur.fetchone()

    if not worker:

        await query.message.reply_text(
            "❗ Профил топилмади."
        )

        return ConversationHandler.END

    context.user_data["edit_worker"] = {}

    await query.message.reply_text(
        "✏️ Профилни таҳрирлаш\n\n"
        f"Ҳозирги исм: {worker[0]}\n\n"
        "Янги исмни ёзинг:"
    )

    return EDIT_WORKER_NAME


async def edit_worker_name(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    text = update.message.text.strip()

    if not text:

        await update.message.reply_text(
            "❗ Исмни бўш қолдирманг."
        )

        return EDIT_WORKER_NAME

    context.user_data[
        "edit_worker"
    ]["name"] = text

    await update.message.reply_text(
        "📞 Янги телефон рақамингизни ёзинг:"
    )

    return EDIT_WORKER_PHONE


async def edit_worker_phone(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    phone = update.message.text.strip()

    if len(re.sub(r"\D", "", phone)) < 7:

        await update.message.reply_text(
            "❗ Телефон рақами нотўғри. "
            "Қайта ёзинг:"
        )

        return EDIT_WORKER_PHONE

    context.user_data[
        "edit_worker"
    ]["phone"] = phone

    await update.message.reply_text(
        "🔧 Янги хизматингизни ёзинг:"
    )

    return EDIT_WORKER_SERVICE


async def edit_worker_service(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    service = update.message.text.strip()

    if not service:

        await update.message.reply_text(
            "❗ Хизматни бўш қолдирманг."
        )

        return EDIT_WORKER_SERVICE

    context.user_data[
        "edit_worker"
    ]["service"] = service

    await update.message.reply_text(
        "📍 Янги ҳудудингизни ёзинг:"
    )

    return EDIT_WORKER_AREA


async def edit_worker_area(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    area = update.message.text.strip()

    if not area:

        await update.message.reply_text(
            "❗ Ҳудудни бўш қолдирманг."
        )

        return EDIT_WORKER_AREA

    context.user_data[
        "edit_worker"
    ]["area"] = area

    await update.message.reply_text(
        "💰 Янги хизмат нархингизни ёзинг:"
    )

    return EDIT_WORKER_PRICE


async def edit_worker_price(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    price = update.message.text.strip()

    if not price:

        await update.message.reply_text(
            "❗ Нарҳни бўш қолдирманг."
        )

        return EDIT_WORKER_PRICE

    data = context.user_data[
        "edit_worker"
    ]

    data["price"] = price

    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                UPDATE workers
                SET
                    name=%s,
                    phone=%s,
                    service=%s,
                    area=%s,
                    price=%s
                WHERE id=(
                    SELECT id
                    FROM workers
                    WHERE telegram_id=%s
                    ORDER BY id DESC
                    LIMIT 1
                )
                """,
                (
                    data["name"],
                    data["phone"],
                    data["service"],
                    data["area"],
                    data["price"],
                    user.id,
                ),
            )

        conn.commit()

    # Save values before clearing
    name = data["name"]
    phone = data["phone"]
    service = data["service"]
    area = data["area"]
    price = data["price"]

    context.user_data.clear()

    await update.message.reply_text(
        "✅ Профилингиз муваффақиятли "
        "янгиланди!\n\n"
        f"👤 Исм: {name}\n"
        f"📞 Телефон: {phone}\n"
        f"🔧 Хизмат: {service}\n"
        f"📍 Ҳудуд: {area}\n"
        f"💰 Нархи: {price}",
        reply_markup=main_keyboard(),
    )

    return ConversationHandler.END


# ============================================================
# ACTIVE / INACTIVE
# ============================================================

async def toggle_worker_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    query = update.callback_query

    await query.answer()

    user = update.effective_user

    try:

        worker_id = int(
            query.data.split(":")[1]
        )

    except Exception:

        await query.message.reply_text(
            "❗ Профил рақами нотўғри."
        )

        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                UPDATE workers
                SET
                    is_active=NOT COALESCE(
                        is_active,
                        TRUE
                    )
                WHERE id=%s
                  AND telegram_id=%s
                RETURNING is_active
                """,
                (
                    worker_id,
                    user.id,
                ),
            )

            result = cur.fetchone()

        conn.commit()

    if not result:

        await query.message.reply_text(
            "❗ Профил топилмади."
        )

        return

    await my_profile(
        update,
        context,
    )


# ============================================================
# PROFILE MAIN MENU
# ============================================================

async def profile_main_menu(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    query = update.callback_query

    await query.answer()

    await query.message.reply_text(
        "🛠 Osh Service ботга хуш келибсиз!\n\n"
        "Керакли хизматни танланг:",
        reply_markup=main_keyboard(),
    )


# ============================================================
# ANNOUNCEMENTS
# ============================================================

async def announcement_start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    context.user_data.clear()

    await update.message.reply_text(
        "📢 Эълон бериш\n\n"
        "👤 Исмингизни ёзинг:"
    )

    return ANN_NAME


async def ann_name(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    name = update.message.text.strip()

    if not name:

        await update.message.reply_text(
            "❗ Исмни бўш қолдирманг."
        )

        return ANN_NAME

    context.user_data["ann_name"] = name

    await update.message.reply_text(
        "📞 Телефон рақамингизни ёзинг:"
    )

    return ANN_PHONE


async def ann_phone(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    phone = update.message.text.strip()

    if len(re.sub(r"\D", "", phone)) < 7:

        await update.message.reply_text(
            "❗ Телефон рақами нотўғри. "
            "Қайта ёзинг:"
        )

        return ANN_PHONE

    context.user_data["ann_phone"] = phone

    await update.message.reply_text(
        "🔧 Қайси хизмат/иш бўйича эълон?\n"
        "Масалан: Электрик",
        reply_markup=worker_services_keyboard(),
    )

    return ANN_SERVICE


async def ann_service(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    service = update.message.text.strip()

    if not service:

        await update.message.reply_text(
            "❗ Хизматни киритинг."
        )

        return ANN_SERVICE

    context.user_data[
        "ann_service"
    ] = service

    await update.message.reply_text(
        "📍 Манзилни ёзинг:"
    )

    return ANN_ADDRESS


async def ann_address(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    address = update.message.text.strip()

    if not address:

        await update.message.reply_text(
            "❗ Манзилни бўш қолдирманг."
        )

        return ANN_ADDRESS

    context.user_data[
        "ann_address"
    ] = address

    await update.message.reply_text(
        "💰 Бюджет/нархни ёзинг:"
    )

    return ANN_BUDGET


async def ann_budget(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    budget = update.message.text.strip()

    if not budget:

        await update.message.reply_text(
            "❗ Бюджетни киритинг."
        )

        return ANN_BUDGET

    context.user_data[
        "ann_budget"
    ] = budget

    await update.message.reply_text(
        "📝 Эълон тафсилотларини ёзинг:"
    )

    return ANN_DETAILS


async def ann_details(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    details = update.message.text.strip()

    if not details:

        await update.message.reply_text(
            "❗ Тафсилотларни ёзинг."
        )

        return ANN_DETAILS

    context.user_data[
        "ann_details"
    ] = details

    data = context.user_data
    user = update.effective_user

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                INSERT INTO announcements
                (
                    telegram_id,
                    name,
                    phone,
                    service,
                    address,
                    budget,
                    details
                )
                VALUES (%s,%s,%s,%s,%s,%s,%s)
                RETURNING id
                """,
                (
                    user.id,
                    data["ann_name"],
                    data["ann_phone"],
                    data["ann_service"],
                    data["ann_address"],
                    data["ann_budget"],
                    data["ann_details"],
                ),
            )

            ann_id = cur.fetchone()[0]

        conn.commit()

    # --------------------------------------------------------
    # ADMIN NOTIFICATION
    # --------------------------------------------------------

    if ADMIN_ID:

        try:

            await context.bot.send_message(
                chat_id=ADMIN_ID,
                text=(
                    f"📢 ЯНГИ ЭЪЛОН #{ann_id}\n\n"
                    f"👤 {data['ann_name']}\n"
                    f"📞 {data['ann_phone']}\n"
                    f"🔧 {data['ann_service']}\n"
                    f"📍 {data['ann_address']}\n"
                    f"💰 {data['ann_budget']}\n"
                    f"📝 {data['ann_details']}"
                ),
            )

        except Exception as exc:

            logger.exception(
                "Admin announcement "
                "notification failed: %s",
                exc,
            )

    await update.message.reply_text(
        f"✅ Эълонингиз қабул қилинди!\n"
        f"Эълон рақами: #{ann_id}",
        reply_markup=main_keyboard(),
    )

    context.user_data.clear()

    return ConversationHandler.END


# ============================================================
# CONTACT
# ============================================================

async def contact(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    await update.message.reply_text(
        "📞 Алоқа\n\n"
        "Администратор билан боғланиш учун "
        "шу ботда хабар қолдиринг."
    )


# ============================================================
# ADMIN CHECK
# ============================================================

async def admin_only(
    update: Update,
):
    return (
        ADMIN_ID
        and update.effective_user
        and update.effective_user.id == ADMIN_ID
    )


# ============================================================
# ADMIN WORKERS
# ============================================================

async def admin_workers(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    if not await admin_only(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                SELECT
                    id,
                    telegram_id,
                    name,
                    phone,
                    service,
                    area,
                    price,
                    COALESCE(is_active, TRUE),
                    created_at
                FROM workers
                ORDER BY id DESC
                """
            )

            rows = cur.fetchall()

    if not rows:

        await update.message.reply_text(
            "Усталар йўқ."
        )

        return

    lines = [
        "👨‍🔧 УСТАЛАР\n"
    ]

    for row in rows:

        (
            wid,
            tid,
            name,
            phone,
            service,
            area,
            price,
            active,
            created,
        ) = row

        status = "🟢" if active else "🔴"

        lines.append(
            f"#{wid} {status} {name} — "
            f"{service} — {area} — {price}\n"
            f"📞 {phone}\n"
            f"🆔 {tid}"
        )

    await update.message.reply_text(
        "\n\n".join(lines)[:4000]
    )


# ============================================================
# ADMIN STATS
# ============================================================

async def admin_stats(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    if not await admin_only(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                "SELECT COUNT(*) FROM workers"
            )

            workers_count = cur.fetchone()[0]

            cur.execute(
                """
                SELECT COUNT(*)
                FROM workers
                WHERE COALESCE(
                    is_active,
                    TRUE
                )=TRUE
                """
            )

            active_count = cur.fetchone()[0]

            cur.execute(
                "SELECT COUNT(*) FROM orders"
            )

            orders_count = cur.fetchone()[0]

            cur.execute(
                """
                SELECT COUNT(*)
                FROM orders
                WHERE status='new'
                """
            )

            new_orders = cur.fetchone()[0]

            cur.execute(
                """
                SELECT COUNT(*)
                FROM orders
                WHERE status='accepted'
                """
            )

            accepted = cur.fetchone()[0]

            cur.execute(
                "SELECT COUNT(*) FROM announcements"
            )

            announcements_count = cur.fetchone()[0]

    await update.message.reply_text(
        "📊 СТАТИСТИКА\n\n"
        f"👨‍🔧 Усталар: {workers_count}\n"
        f"🟢 Фаол усталар: {active_count}\n"
        f"📦 Буюртмалар: {orders_count}\n"
        f"🆕 Янги буюртмалар: {new_orders}\n"
        f"✅ Қабул қилинган: {accepted}\n"
        f"📢 Эълонлар: {announcements_count}"
    )


# ============================================================
# ADMIN ORDERS
# ============================================================

async def admin_orders(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    if not await admin_only(update):
        return

    with get_connection() as conn:
        with conn.cursor() as cur:

            cur.execute(
                """
                SELECT
                    id,
                    name,
                    phone,
                    service,
                    address,
                    problem,
                    status,
                    accepted_worker_name,
                    created_at
                FROM orders
                ORDER BY id DESC
                LIMIT 30
                """
            )

            rows = cur.fetchall()

    if not rows:

        await update.message.reply_text(
            "Буюртмалар йўқ."
        )

        return

    lines = [
        "📦 СЎНГГИ БУЮРТМАЛАР\n"
    ]

    for row in rows:

        (
            oid,
            name,
            phone,
            service,
            address,
            problem,
            status,
            accepted,
            created,
        ) = row

        lines.append(
            f"#{oid} | {status}\n"
            f"{service} | {name}\n"
            f"📞 {phone}\n"
            f"📍 {address}\n"
            f"📝 {problem}\n"
            f"👨‍🔧 {accepted or '-'}"
        )

    await update.message.reply_text(
        "\n\n".join(lines)[:4000]
    )


# ============================================================
# ERROR HANDLER
# ============================================================

async def error_handler(
    update: object,
    context: ContextTypes.DEFAULT_TYPE,
):
    logger.error(
        "Unhandled exception while processing update:",
        exc_info=context.error,
    )


# ============================================================
# BUILD APPLICATION
# ============================================================

def build_application():

    application = (
        Application
        .builder()
        .token(TOKEN)
        .build()
    )

    # ========================================================
    # WORKER REGISTRATION
    # ========================================================

    worker_conv = ConversationHandler(

        entry_points=[
            MessageHandler(
                filters.Regex(
                    r"^👨‍🔧 Уста бўлиб рўйхатдан ўтиш$"
                ),
                worker_register_start,
            )
        ],

        states={

            WORKER_NAME: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_name,
                )
            ],

            WORKER_PHONE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_phone,
                )
            ],

            WORKER_SERVICE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_service,
                )
            ],

            WORKER_AREA: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_area,
                )
            ],

            WORKER_PRICE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    worker_price,
                )
            ],
        },

        fallbacks=[
            CommandHandler(
                "start",
                start,
            )
        ],
    )

    # ========================================================
    # CUSTOMER ORDER
    # ========================================================

    order_conv = ConversationHandler(

        entry_points=[
            MessageHandler(
                filters.Regex(
                    r"^(🔧|⚡|📱|💻|🧹|🪑)"
                ),
                order_from_service,
            )
        ],

        states={

            ORDER_NAME: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_name,
                )
            ],

            ORDER_PHONE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_phone,
                )
            ],

            ORDER_ADDRESS: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_address,
                )
            ],

            ORDER_PROBLEM: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    customer_problem,
                )
            ],
        },

        fallbacks=[
            CommandHandler(
                "start",
                start,
            )
        ],
    )

    # ========================================================
    # ANNOUNCEMENT
    # ========================================================

    announcement_conv = ConversationHandler(

        entry_points=[
            MessageHandler(
                filters.Regex(
                    r"^📢 Эълон бериш$"
                ),
                announcement_start,
            )
        ],

        states={

            ANN_NAME: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_name,
                )
            ],

            ANN_PHONE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_phone,
                )
            ],

            ANN_SERVICE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_service,
                )
            ],

            ANN_ADDRESS: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_address,
                )
            ],

            ANN_BUDGET: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_budget,
                )
            ],

            ANN_DETAILS: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    ann_details,
                )
            ],
        },

        fallbacks=[
            CommandHandler(
                "start",
                start,
            )
        ],
    )

    # ========================================================
    # EDIT PROFILE
    # ========================================================

    edit_conv = ConversationHandler(

        entry_points=[
            CallbackQueryHandler(
                start_edit_profile,
                pattern=r"^edit_profile$",
            )
        ],

        states={

            EDIT_WORKER_NAME: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    edit_worker_name,
                )
            ],

            EDIT_WORKER_PHONE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    edit_worker_phone,
                )
            ],

            EDIT_WORKER_SERVICE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    edit_worker_service,
                )
            ],

            EDIT_WORKER_AREA: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    edit_worker_area,
                )
            ],

            EDIT_WORKER_PRICE: [
                MessageHandler(
                    filters.TEXT & ~filters.COMMAND,
                    edit_worker_price,
                )
            ],
        },

        fallbacks=[
            CommandHandler(
                "start",
                start,
            )
        ],
    )

    # ========================================================
    # ADD CONVERSATIONS
    # ========================================================

    application.add_handler(
        worker_conv
    )

    application.add_handler(
        order_conv
    )

    application.add_handler(
        announcement_conv
    )

    application.add_handler(
        edit_conv
    )

    # ========================================================
    # CALLBACKS
    # ========================================================

    application.add_handler(
        CallbackQueryHandler(
            accept_order_callback,
            pattern=r"^accept_order:",
        )
    )

    application.add_handler(
        CallbackQueryHandler(
            toggle_worker_callback,
            pattern=r"^toggle_worker:",
        )
    )

    application.add_handler(
        CallbackQueryHandler(
            profile_main_menu,
            pattern=r"^profile_main_menu$",
        )
    )

    # ========================================================
    # COMMANDS
    # ========================================================

    application.add_handler(
        CommandHandler(
            "start",
            start,
        )
    )

    application.add_handler(
        CommandHandler(
            "help",
            help_command,
        )
    )

    application.add_handler(
        CommandHandler(
            "workers",
            admin_workers,
        )
    )

    application.add_handler(
        CommandHandler(
            "stats",
            admin_stats,
        )
    )

    application.add_handler(
        CommandHandler(
            "orders",
            admin_orders,
        )
    )

    # ========================================================
    # MAIN MENU
    # ========================================================

    application.add_handler(
        MessageHandler(
            filters.Regex(
                r"^🔧 Хизматлар$"
            ),
            show_services,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(
                r"^👨‍🔧 Уста чақириш$"
            ),
            worker_menu,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(
                r"^👤 Менинг профилим$"
            ),
            my_profile,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(
                r"^Алоқа$"
            ),
            contact,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.Regex(
                r"^⬅️ Бош меню$"
            ),
            start,
        )
    )

    # ========================================================
    # ERROR HANDLER
    # ========================================================

    application.add_error_handler(
        error_handler
    )

    return application


# ============================================================
# MAIN
# ============================================================

def main():

    # --------------------------------------------------------
    # DATABASE
    # --------------------------------------------------------

    init_database()

    # --------------------------------------------------------
    # APPLICATION
    # --------------------------------------------------------

    application = build_application()

    # --------------------------------------------------------
    # RENDER WEBHOOK
    # --------------------------------------------------------

    if RENDER_EXTERNAL_URL:

        webhook_url = (
            f"{RENDER_EXTERNAL_URL}"
            "/telegram-webhook"
        )

        logger.info(
            "Starting webhook: %s",
            webhook_url,
        )

        application.run_webhook(
            listen="0.0.0.0",
            port=PORT,
            url_path="telegram-webhook",
            webhook_url=webhook_url,
        )

    # --------------------------------------------------------
    # LOCAL / POLLING
    # --------------------------------------------------------

    else:

        logger.info(
            "Starting polling"
        )

        application.run_polling(
            drop_pending_updates=True
        )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    main()
